---
# Predecessor Crons role handlers

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart predecessor-crons
  systemd:
    name: predecessor-crons
    state: restarted
    daemon_reload: yes

- name: Stop predecessor-crons
  systemd:
    name: predecessor-crons
    state: stopped
