---
# Common role handlers

- name: Restart belica-bot
  systemd:
    name: belica-bot
    state: restarted
    daemon_reload: yes
  ignore_errors: yes  # Service may not exist yet during initial setup

- name: Restart predecessor-crons
  systemd:
    name: predecessor-crons
    state: restarted
    daemon_reload: yes
  ignore_errors: yes  # Service may not exist yet during initial setup
